require("navigator").setup({
	width = 1,
	default_mapping = true,
	keymaps = {
		{ key = "gr", func = "references()" },
		{ key = "<C-RightMouse>", func = "references()" },
		{ mode = "i", key = "<M-k>", func = "signature_help()" },
		{ key = "<c-k>", func = "signature_help()" },
		{ key = "K", func = "hover({ popup_opts = { border = single, max_width = 80 }})" },
		{ key = "g$.", func = "document_symbol()" },
		{ key = "g$*", func = "workspace_symbol()" },
		{ key = "gd", func = "definition()" },
		{ key = "<C-LeftMouse>", func = "definition()" },
		{ key = "gD", func = "declaration({ border = 'rounded', max_width = 80 })" },
		{ key = "gp", func = "require('navigator.definition').definition_preview()" },
		{ key = "gT", func = "require('navigator.treesitter').buf_ts()" },
		{ key = "ga", mode = "n", func = "require('navigator.codeAction').code_action()" },
		{ key = "ga", mode = "v", func = "range_code_action()" },
		{ key = "gA", mode = "n", func = "require('navigator.codelens').run_action()" },
		{ key = "gR", func = "rename()" },
		{ key = "gI", func = "incoming_calls()" },
		{ key = "gO", func = "outgoing_calls()" },
		{ key = "gi", func = "implementation()" },
		{ key = "<M-LeftMouse>", func = "implementation()" },
		{ key = "g:", func = "type_definition()" },
		{ key = "gl.", func = "require('navigator.diagnostics').show_line_diagnostics()" },
		{ key = "gl*", func = "require('navigator.diagnostics').show_diagnostic()" },
		{ key = "]d", func = "diagnostic.goto_next({ border = 'rounded', max_width = 80})" },
		{ key = "[d", func = "diagnostic.goto_prev({ border = 'rounded', max_width = 80})" },
		{ key = "]r", func = "require('navigator.treesitter').goto_next_usage()" },
		{ key = "[r", func = "require('navigator.treesitter').goto_previous_usage()" },
		{ key = "g/", func = "require('navigator.dochighlight').hi_symbol()" },
		{ key = "<space>p>", func = "add_workspace_folder()" },
		{ key = "<Space>p<", func = "remove_workspace_folder()" },
		{ key = "<Space>rf", func = "formatting()", mode = "n" },
		{ key = "<Space>rf", func = "range_formatting()", mode = "v" },
		{ key = "<Space>rr", func = "require('navigator.rename').rename()" },
		{ key = "<Space>pl", func = "print(vim.inspect(vim.lsp.buf.list_workspace_folders()))" },
	},
	lspinstall = true,
	icons = {
		icons = true,
		code_action_icon = "",
		code_lens_action_icon = "",
		diagnostic_head = "",
		diagnostic_err = "",
		diagnostic_warn = "",
		diagnostic_info = "",
		diagnostic_hint = "﯂",
		diagnostic_head_severity_1 = "",
		diagnostic_head_severity_2 = "",
		diagnostic_head_severity_3 = "",
		diagnostic_head_description = "瘟",
		diagnostic_virtual_text = "",
		diagnostic_file = "",
		value_changed = "פֿ",
		value_definition = "",
		match_kinds = {
			var = " ",
			method = "ƒ ",
			["function"] = " ",
			parameter = "  ",
			associated = "&",
			namespace = " ",
			type = " ",
			field = "﫻",
		},
		treesitter_default = "",
	},
})
